### ISSUE TITLE
Emission Rates Mode Incomplete Output

### ISSUE THREAD

**Issue by pml-aq** [USEPA/EPA_MOVES_Model#34]
When generating Greenhouse Gases emission rates with MOVES3.0.2, I’m getting an incomplete **ratesperdistance** output table. It was tested on multiple computers and still running into the same issue. Specifically, the rates for roadtype = 5 _stop_ after hour 4 and speedbin 10. There are **no** more rates produced for roadtype 5 after hour 4. The same emission rates were generated using Moves2014a and it returned results for all hours, road types, and speed bins. Can you provide some assistance as to why there could be incomplete rate table generated by MOVES3.0.2. Note: I’m using the same input database base as for emission inventory analysis, which completed correctly. 

If needed I can also provide input and output database to help with review.

**Comment by EvanGrahamMurray** [comment]
Hi @pml-aq, can you send us your runspec and input database? That would help diagnose the issue.

You can reply to this comment and attach them directly on Github, or if you'd prefer you can send them to the MOVES inbox at mobile@epa.gov. If you email us, please include the github issue number (34) in the subject line.

Thanks!

**Comment by pml-aq** [comment]
Hi @EMurrayEPA just sent you an email with the runspec and input database. Thank you.

**Comment by danielbizercox** [comment]
The most likely cause for missing results in rates mode with MOVES3 is due to lack of activity assigned to those particular rows. I would recommend checking your avgspeeddistribution input to make sure you don't have 0 activity assigned to speedBinIDs 11-16 on roadTypeID 5 and those particular hours. If you have 0s in that input, MOVES will not assign activity to those speed bins, and therefore it won't be able to calculate an emission rate for it.

If the activity for those rows is truly 0, but you still want to calculate emission rates for them, we recommend setting the speed distribution for them to something very small, such as 0.000001. This will allow MOVES to still calculate an emission rate for this row.
