### ISSUE TITLE
Drive Schedule to Operating Mode Underlying Implementation

### ISSUE THREAD

**Issue by ct135** [USEPA/EPA_MOVES_Model#50]
I have been working with the MOVES model on the Project Scale and using the Link Drive Schedule Importer for entering vehicle activity. From my reading of the MOVES documentation, my understanding is the underlying way MOVES works is by translating this Drive Schedule into an Operating Mode Distribution and then calculating emissions using this OpMode Distribution. 

When considering how to calculate the emissions corresponding to a vehicle driving following the inputted drive schedule, I assumed that the emissions would be calculated by the emission rates for a given operating mode multiplied by the distance driven in that operating mode and then summed over all the operating modes. However, the operating mode distribution is based off of  the proportion of time travelling in a given operating mode rather which isn’t the same as the proportion of distance travelled in a given operating mode. Given this difference, wouldn’t the emissions quantity of a fleet driving according to a driving cycle be different than that of driving according to the operating mode pattern? I have included a very simplified example below of how I understand MOVES to be working that more clearly shows what I was described above using numbers. 

I was wondering how MOVES actually addresses this issue and please correct me if I’m wrong in my understanding of how MOVES work.
![Example](https://user-images.githubusercontent.com/62026524/180582550-e22a4c4d-fc70-459d-8d4f-2d44757bea97.jpg)

**Comment by EvanGrahamMurray** [comment]
Hi Catherine, 

Our operating mode emission rates for the running process are defined in units of grams (or kilojoules in the case of energy consumption) per Source Hours Operating (SHO). When MOVES calculates an operating mode distribution based on a drive cycle, it calculates the amount of time, in hours, in each operating mode and then multiplies that time by the emission rates. 

You can find information on units in our emission rate tables and most other tables in the MOVES database in our [MOVES Database Tables](https://github.com/USEPA/EPA_MOVES_Model/blob/master/docs/MOVESDatabaseTables.md) documentation.  This is a large document, so [here's a link to the emissionrate](https://github.com/USEPA/EPA_MOVES_Model/blob/master/docs/MOVESDatabaseTables.md#emissionrate) table which includes the unit information for our base rates.

**Comment by ct135** [comment]
Thank you for your response and for clarifying on the units for base emission rates. 

One quick follow-up question:

How is the drive schedule/op-mode distribution used to calculate the emission quantity for a given link? In other words, how is the drive schedule mapped to the link and how does the link length used in the calculation of emissions?

**Comment by EvanGrahamMurray** [comment]
Running activity for a link can be defined using average speed, a drive cycle, or an operating mode distribution. A link's average speed and distance is provided in the link table directly, while drive schedules and operating mode distributions are provided in separate tables (driveschedulesecondlink and opmodedistribution, respectively). Each table has a linkID column to map drive cycles or operating mode distributions to particular links.

If an average speed or operating mode distribution is provided, MOVES uses the average speed in the link table for activity calculations. If a drive cycle is provided, MOVES uses the average speed of the drive cycle and disregards the average speed provided in the link table. When this is the case, you will see a message like `Link X will obtain average speed and grade from its driving schedule` in the Project Data Manager.

For each link, MOVES calculates the link VMT as the smaller of (A) the product of the link length and link volume, or (B) the product of the link average speed and the link volume. A project scale run is always defined as one hour, so whichever of these options is smaller is the physical constraint on VMT. For example, a link with an average speed of 5 mph and a length of 50 miles will use Option B, because the maximum per-vehicle miles traveled is 5 miles. Likewise, if a link is 5 miles long with an average speed of 50 mph, MOVES will use Option A because a vehicle will travel the full 5 miles in less than an hour.

MOVES then calculates Source Hours Operating (SHO) as the VMT calculated above divided by the average speed for each link. Once again, when a drive schedule is provided the drive cycle's average speed is used instead of the average speed in the link table.

**Comment by ct135** [comment]
Hello,

Thank you so much for your response and in-depth explanation of how MOVES works.

For context, we are currently in the process of designing a research experiement that uses MOVES as our emission model. As a follow up, we were wondering if you had any official documents, technical reports, or research papers, that you can point us to that explains the underlying processes of MOVES that you described above, in similar detail. 

We have looked through a few of the MOVES overall guidelines, MOVES for Project Scale PM Analysis guidelines, and the technical guidelines already but haven't been able to find this so far, so we were hoping that you might be able to direct us to a resource that we can cite an explanation of how MOVES calculates emissions from a driving schedule in our work.

**Comment by danielbizercox** [comment]
The [MOVES Overview Report](https://nepis.epa.gov/Exe/ZyPDF.cgi?Dockey=P1011KV2.pdf) describes at a high level how activity is calculated in source hours and applied to emission rates to calculate total emissions (section 3.1). 

You can also take a look at [Draft Design and Implementation Plan for EPA’s Multi-Scale Motor Vehicle and Equipment Emission System (MOVES)](https://nepis.epa.gov/Exe/ZyPDF.cgi?Dockey=P1000527.pdf). While old and out of date, it does describe in more detail how MOVES goes from drive schedules to operating mode distributions to source hours in Section 7.1.2. Specifically, see the Microscale `Tag-4` and `Tag-7` sections. Note that in this document, Default Scale is referred to as "Macroscale", County Scale is "Mesoscale", and Project Scale is "Microscale".
