### ISSUE TITLE
Are LinkIDs unique?

### ISSUE THREAD

**Issue by hotmedal** [USEPA/EPA_MOVES_Model#74]
Are LinkIDs unique and do they represent real roads that can be identified? Can I use a linkID and figure out the actual real-world road?

**Comment by danielbizercox** [comment]
LinkIDs are assigned by the modeler when constructing a project scale input database using the `link` table. They must be unique for each run, but can be used to represent a variety of modeling methods (e.g., one roadway segment, or one lane, or one pattern of travel activity through a signalized intersection, etc.). If you are asking this question while reviewing MOVES output, you will need to refer to the run documentation (hopefully it is available) or contact the modeler who performed the MOVES run to understand what their specific linkIDs represent.

For reference, whatever modelling approach is used, we recommend filling out the description column when populating the `link` table, so that it is easier to understand what the emissions on that link represent when post-processing MOVES results. For more information on how to use Project Scale, see Module 7 of the MOVES training materials: https://www.epa.gov/moves/moves4-hands-training-course

**Comment by hotmedal** [comment]
I'm performing the run myself but not doing Project Scale, I'm using default scale with emission rate calculation. In the output I can see the linkIDs which are related to the countyID. I cannot find any documentation saying how these IDs were assigned.

**Comment by danielbizercox** [comment]
Sorry, I misunderstood your use case. 

In Default Scale rates mode, the linkID in the output is composed by the countyID, roadTypeID, and avgSpeedBinID.

**Comment by hotmedal** [comment]
I see. So they do not map to real world roads, instead one linkID represents the average road with that road type, speed bin, and geographic location?

**Comment by danielbizercox** [comment]
Correct, the linkIDs at Default Scale do not map to real world roads. The only additional information that the linkID column provides is the countyID, as the roadTypeID and avgSpeedBinID are always present and populated in the rates tables.

In thinking about the best way to conceptualize MOVES output tables, take the rateperdistance table for example. For each row in that table, the `ratePerDistance` value represents the g/mi (or whatever units you have selected in the RunSpec) associated with a specific:
* run and/or scenario
* year
* month
* day
* hour
* county
* pollutant
* process
* source type
* reg class
* fuel type
* model year
* road type
* avgSpeedBin
* temperature
* humidity

The way that the county information is incorporated in this table is via the linkID column, instead of having a specific countyID or zoneID field.

Note that if you don't select one of these fields in the RunSpec's Output Emissions Detail, the field will be NULL, and the `ratePerDistance` value will represent the average rate over all possible values in that field. For example, if you don't select model year in the output, the emission rates will be averaged across all model years.

**Comment by hotmedal** [comment]
Thank you for your explanation.
